### ISSUE TITLE
Path of MainActivity.java have changed in cordova-android@7.0.0 

### ISSUE THREAD

**Issue by tong9977** [bsorrentino/ionic-broadcaster-sample#1]
path of MainActivity.java  in cordova-android@7.0.0  is /platforms/android/app/src/main/java/io/ionic/starter/MainActivity.java 

so I change one line of code at android_after_plugin_installed.js
var rel = path.join('src', 'io', 'ionic', 'starter');
to
var rel = path.join('app','src','main','java','io', 'ionic', 'starter');

It's work for me

**Comment by bsorrentino** [comment]
Hi @tong9977

thanks for feedback

Consider that this is a perfect case to do a **PR**
