### ISSUE TITLE
broadcaster plugin is not working in ios. i amgetting unhandle promise rejection issue for addlistenerr 

### ISSUE THREAD

**Issue by prameela-reddy** [bsorrentino/ionic-broadcaster-sample#6]
this.platform.ready().then(() => {

    this.broadcaster.addEventListener('NucleiBroadCaster').subscribe((event) => { 
      console.log("NucleiBroadCaster "+event);
      
    //  // this.iPalHashCodeBasedRedirection(event.hashcode);
      });
    });

**Comment by bsorrentino** [comment]
Hi @prameela-reddy 

Are you using the last version of plugin 4.0.0 ?

Which IOS version ?

**Comment by prameela-reddy** [comment]
Hi

I am using version 5.16.0

**Comment by bsorrentino** [comment]
Hi @prameela-reddy 

Using `cordova-broadcaster-plugin@4.4.0` and `cordova-ios@4.5.5` works as expected

what are the versions in your case?

**Comment by bsorrentino** [comment]
close for inactivity
